Repository openfisca/legislation-explorer, pull requests merged in 2018-10, with the labels that each got.

#192 Add editorial content on variables and parameters
  src/assets/lang/en.json
  src/assets/lang/fr.json
  src/assets/style.css
  src/components/parameter.jsx
  src/components/variable.jsx
  src/openfisca-proptypes.js
Labels: flow:team:doing, kind:solution

#200 Match pathname before :name in routes
  src/routes.jsx
Labels: flow:contrib:doing, kind:bug

#206 Update outdated minor versions
  package-lock.json
  package.json
Labels: kind:improvement, level:starter

#205 Use configured basename in server-side rendering
  src/server/index.js
  src/server/render.jsx
Labels: flow:team:reviewing, kind:bug
